shallow_clone: true
clone_folder: c:\projects\Voodoo-Mock

install:
  #let's use the pre-installed mingw
  - ps: $env:PATH = 'C:\MinGW\bin;C:\MinGW\mingw32\bin;C:\MinGW\msys\1.0\bin;' + $env:PATH
  #we copy mingw32-make to have a "make" executable
  - cmd: copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe

  #needed to download other deps
  - cinst wget

  #let's install the LLVM distribution
  - cmd: mkdir LLVM_DOWNLOAD
  - cmd: cd LLVM_DOWNLOAD
  - cmd: wget "http://llvm.org/releases/3.6.0/LLVM-3.6.0-win32.exe"
  - cmd: 7z x LLVM-3.6.0-win32.exe
  - cmd: ren $_OUTDIR LLVM-3.6.0
  - cmd: move LLVM-3.6.0 c:\
  - ps: $env:PATH = 'c:\LLVM-3.6.0\bin;' + $env:PATH

  #python modules
  - cmd: C:\Python27\scripts\pip install futures
  - cmd: C:\Python27\scripts\pip install clang==3.5
  - ps: $env:PATH = 'c:\Python27\Lib\site-packages;' + $env:PATH

build_script:
  #build / test Voodoo-Mock
#  - cmd: sh -c "g++ -E -x c++ - -v < /dev/null"
#  - cmd: type  c:\mingw\include\unistd.h
#  - cmd: sh -c "grep -rnC20 _exit c:/mingw/include"
  - ps: cd "c:\projects\Voodoo-Mock"
  - cmd: sh -c "make V=1"
